### ISSUE TITLE
Add Pundit for authorization

### ISSUE THREAD

**Issue by cubadomingo** [cubadomingo/words_and_moves#100]
I think we should add the Pundit gem for authorization. If a user tries to subscribe, create a new post/event, basically any feature that require a user to sign in, it should have him sign in/sign up. I think all views should be opened up, so for example anybody can view posts/events but only users can comment/like/all that. and if they try to then they'll get redirected to the sign in/sign up page.

**Comment by tmobaird** [comment]
I don't even think we actually need to do that. Devise takes care of all authentication, if you want a controller to require authentication for an action, simply add a before action with `authenticate_user!`. Other than that, for the pages anyone can view, we can just not include this authenticate_user method
