### ISSUE TITLE
Unsubscribe_path Not Found

### ISSUE THREAD

**Issue by tmobaird** [cubadomingo/words_and_moves#114]
The `unsubscribe_path` is not being found from our routes. This path appears in some of our views and should be updated to reflect a new route, or the routes should be updated to add this unsubscribe path. For the time being I am removing the two spots where this is used and replacing it with a dead link. I will tag the commit with these changes so that the files changes can be seen.

**Comment by cubadomingo** [comment]
So I was just looking at fixing this right now but the path seems to be working for me bro. I'm able to subscribe and then unsubscribe from the region. Also It's being matched in the routes. What issues were you having?

<img width="609" alt="screen shot 2016-08-18 at 11 56 06 am" src="https://cloud.githubusercontent.com/assets/15992549/17786677/ca81c2e6-653a-11e6-9d02-3bb4a8942f4a.png">

**Comment by tmobaird** [comment]
I was just getting an error for a couple of links to the unsubscribe path. I didn't look too much into it

**Comment by cubadomingo** [comment]
I'll pull your branch and see if I can replicate. Would you happen to know what kind of error you were getting by chance?

**Comment by tmobaird** [comment]
I think it was just no route matches `unsubscribe_path`. Check out how it works before the changes I made that include this path in the following commit: https://github.com/cubadomingo/words_and_moves/pull/115/commits/c735bd418554c23faa2f6ad0883b967448b8d8e0
