### ISSUE TITLE
RSVPs to Events

### ISSUE THREAD

**Issue by tmobaird** [cubadomingo/words_and_moves#3]
I'm completely spitballing here, so let me know if this sounds dumb, but I think it would be a cool idea to add some sort of RSVPing type functionality to all events. Or maybe this functionality with a more hip name lol. All users would be able to RSVP to events allowing users to see how many people are attending an event, and (possibly) who is attending an event. I think this would definitely be an incentive for users to continually use the site to find the most popular events in their area.

**Comment by cubadomingo** [comment]
I think that's a great idea. Similar to how meet ups has the RSVP button? I think it would be great because you can view events by not only the votes but also how many people plan on attending. Only thing I see that could be an issue is seeing how accurate it is, considering meet ups RSVP's aren't very accurate at all.

**Comment by tmobaird** [comment]
Yeah exactly like that, I think it'd be a cool way to connect with other people. That's a very good point though, meetup's RSVP list can sometimes be inaccurate. I think with this functionality it'd be really nice to have, we'd just have to factor in some user error (ex. User RSVPs even and decides not to go to event)

**Comment by cubadomingo** [comment]
Alright bro, well I'm complete with the idea. How would we go about implementing it, adding a RSVP model that has many User ID's and belongs to an Event?

**Comment by tmobaird** [comment]
Yep, that's all we would need (the RSVP and user_id relationship). Along with an Event having many RSVPs. It's up to you though if you want to name that model RSVP or something else

**Comment by cubadomingo** [comment]
So I went ahead and did the relationships. I think this may work. Let me know what you think
<img width="512" alt="screen shot 2016-07-24 at 11 59 24 am" src="https://cloud.githubusercontent.com/assets/15992549/17084823/41b6dc1a-5196-11e6-9e07-20a8557b4dbe.png">
So a User has many events he can attend and an event has many users that can attend, the join table would be called attend list (can be changed). This way the users will be able to see all the events they plan on attending and an event will be able to see all the users that are attending. Unless I am thinking about the relationship wrong.

**Comment by tmobaird** [comment]
Dude, that looks perfect. I think we might need to change the name of the model though. Just because an Event should have many RSVPs. So when calling `event.rsvps` that would return the to you the list of RSVPs or the AttendList. 

The name could be changed to an array of different things though (RSVP or Attendee).

I also think the calendar and email idea is great! You can open an issue for that if you want, but i think we should put that on the backlog for now because it's not a core functionality.

**Comment by cubadomingo** [comment]
Alright bro, you're right about the name. I'll go ahead and add the model, make the associations, and tag the issue. I'll assign you the PR to make sure everything is right and then you can go ahead and merge it.

**Comment by tmobaird** [comment]
Perfect 👍

**Comment by tmobaird** [comment]
@cubadomingo this should be good now right?

**Comment by cubadomingo** [comment]
Yes! Closing right now.
