### ISSUE TITLE
Page after user signs in

### ISSUE THREAD

**Issue by cubadomingo** [cubadomingo/words_and_moves#32]
Alright so here's what I'm thinking after the user is able to sign in:

It should redirect to a page that looks like this:
<img width="916" alt="screen shot 2016-07-28 at 7 08 42 pm" src="https://cloud.githubusercontent.com/assets/15992549/17232541/c72da1b8-54f6-11e6-9fc2-ff3bb7924d66.png">

Don't mind the double posts and events, or fonts, just an example. I'm thinking we change the navbar once in the feed page to make it look like the one in the example. The links should be the different categories and in the side there should be links to filter the posts and events, along with genres (for the music category atleast). Now this is the page that I'm thinking we do using React. So the initial page load should be rendered on the server side and then all the updating on the page should be client side.

I'm thinking the navbar, user settings and account section should be traditional rails erb, as well as the individual posts themselves.

What do you think about this idea? Let me know if it makes sense or if I'm talking out of my ass, cause I'm still trying to understand react myself haha.

**Comment by cubadomingo** [comment]
Also, [check this out when you get a chance](https://github.com/shakacode/react_on_rails/blob/cd72861076c43cb3765a90ad69cda6a20b3bac95/README.md#client-side-rendering-vs-server-side-rendering).

**Comment by tmobaird** [comment]
I think this looks good, and I completely agree. It'd be cool if we could render the list with react components and poll every couple of seconds so we can upgrade the non-outdated events, up votes/down votes, and new events/posts. I think this would definitely be perfect for that. Do you have react integrated already? and or any approach you'd like to take? I can take a crack at adding the basics of this if you want

**Comment by cubadomingo** [comment]
So I installed the proper gem for making this work and I referenced this issue. If you want to go ahead and start working on this, by all means brother go ahead. I'm going to try and read up a bit more on react along with the gem since it's all still a bit fuzzy to me.

**Comment by tmobaird** [comment]
Shoot, I just realized I had a question about this. Would this page be based on a specific region? or how would we generate this information for the user? Would they have a home region or something and we would just pull events and posts from that region?

**Comment by tmobaird** [comment]
I also really like the change of the navbar color after a sign in lol looks dope

**Comment by cubadomingo** [comment]
So I was actually thinking about this too. Here's my take on it. So what if we mapped a subdomain to a specific region. So DC.wordsandmoves.com would be for the DC and surrounding area.

Now for region I think if we should tag each event with a city id that connects to a region, that way users can sort through events by city. Now the thing is I don't know if the cities should have the region_id, or if they should have sub-regions (DC, Southern Maryland, Northern Virginia), that then connect to the region as a whole.

In terms of post I think they should just have a region ID. No point in filtering the posts into specific  cities.

What do you think about this bro? Let me know if you have a different take on it; I'm all ears.

**Comment by tmobaird** [comment]
Actually new idea. Each user could have a feed that will include all events and posts from the regions they have added to their account

**Comment by cubadomingo** [comment]
Dude that would be perfect!! So someone who's constantly traveling between cities or is between two major regions say SF Bay Area/ Los Angeles can keep up to date.

So what if we keep the Region pages, but the Users dashboard has all the regions he's subscribed to, with his region being the default.

I really like that feature man, great thinking.

**Comment by tmobaird** [comment]
I think we should definitely add cities. And have cities belong to regions. I agree that posts should only belong to regions and events would belong to cities which in turn would belong to a region through a city. We need to start creating these associations in our migrations because I don't believe they are there yet

**Comment by cubadomingo** [comment]
Alright I'll take care of it. What do you think about having subregions? Bay Area(East Bay, SF, Peninsula, Southbay, Northbay) DC(SMaryland, Nova, DC) LA(Downtown, Valley, etc.)

**Comment by tmobaird** [comment]
So here's what I'm thinking for pages.

**User Feed**
- Events by User Selected Regions/Cities
- Posts by User Selected Cities

**Region Event/Post List**
- Events by Region
- Posts by Region

**City Event List**
- Events by City

And that looks good to me. I say we start with a few and built up over time. I'd add NoVA to that list as well

**Comment by cubadomingo** [comment]
Yeah most definitely I say we just focus on the DC area for now. In User Feed the posts should be by region, not city. I think the posts should just have a region id, no association with cities. Other than that everything else looks good.

**Comment by tmobaird** [comment]
Sorry, you're right. That's what I meant 👍

**Comment by tmobaird** [comment]
once the db relations are set. I can start mocking this stuff out, then hopefully bring react into play

**Comment by cubadomingo** [comment]
Alright, I'll have set the relations in a bit. I'm juiced bro, it's getting real!!

**Comment by tmobaird** [comment]
you mind designing the navbar for this part? and possible some of the css for the page?

**Comment by cubadomingo** [comment]
I'm on it.
