### ISSUE TITLE
Missing Migration References

### ISSUE THREAD

**Issue by tmobaird** [cubadomingo/words_and_moves#34]
I think we forgot to add the migration references for posts and events to a category. The schema file currently looks like this for these:

<img width="365" alt="screen shot 2016-07-28 at 11 16 37 pm" src="https://cloud.githubusercontent.com/assets/7366444/17236778/83971e8e-5519-11e6-88e1-d3c7bdb85ed8.png">
<img width="391" alt="screen shot 2016-07-28 at 11 16 26 pm" src="https://cloud.githubusercontent.com/assets/7366444/17236780/87f90726-5519-11e6-8cd5-5a7889fe9eb1.png">

Both of these should eventually have a `category_id` field in them. To do this you probably need to generate two different migrations, one that will add a category reference to events, and one that will add a category reference to posts.

**Comment by cubadomingo** [comment]
Also add Cities model, and reference city_id in events. Reference region_id in posts.
