### ISSUE TITLE
UI color scheme?

### ISSUE THREAD

**Issue by cubadomingo** [cubadomingo/words_and_moves#4]
Hey bro so I think we should most definitely decide on a color scheme for the app. I was thinking about going with the CMYK colors but I'm feeling kind of eh about it. Maybe it's because of my implementation of it. Here's a screen shot of what I have for a navbar, footer, and login page. Thoughts? You think we should just try to tone it done a bit, and maybe just use one strong color or possible none at all? I feel like it could be distracting.

<img width="1307" alt="screen shot 2016-07-23 at 9 40 06 pm" src="https://cloud.githubusercontent.com/assets/15992549/17081230/7204da3e-511e-11e6-8c7b-529ddaf38bae.png">

**Comment by tmobaird** [comment]
I'm not great with design stuff, but I agree that there are a lot of strong colors. I really like the blue and pink color combo, and definitely think the blue you have right now should be the dominant color. Maybe softening the pink color a tiny bit, and/or softening the yellow color could look really good.

Also, did you think we should have some kind of background on our pages?

**Comment by cubadomingo** [comment]
I'm thinking we should most definitely do something about the background. I think that's one of the reasons I'm not liking the color scheme too, the contrast between all the white space and bright colors is unappealing. Let me work on a couple of different schemes and I'll post them here for you to see.

**Comment by tmobaird** [comment]
Sounds good brotha

**Comment by cubadomingo** [comment]
<img width="1096" alt="screen shot 2016-07-25 at 6 19 27 pm" src="https://cloud.githubusercontent.com/assets/15992549/17119522/6c0d882a-5294-11e6-8725-65e1db7b15c1.png">

How does this look for the sign in page bro?

**Comment by tmobaird** [comment]
Dude, I think this looks awesome! That color scheme is perfect
