### ISSUE TITLE
User Profile?

### ISSUE THREAD

**Issue by tmobaird** [cubadomingo/words_and_moves#42]
We might need to add some form of user profile or explore page. We need something that allows the users to add cities and regions to their lists so that we can aggregate posts and events for their feed.

Not sure what the best way to do this would be.

**Comment by cubadomingo** [comment]
I think in the landing page(not the temp one we have now) we should have a box list of cities with their picture, so users can click on them and be redirected to their region page. Maybe call that the explore? So visitors automatically land in the explore page, and users can also check the explore page to find new regions. Maybe a search bar at the top too that automatically searches and shows the regions.

**Comment by tmobaird** [comment]
That's a good idea. Just like on the feed how we have panels for things like "hot", "new", and "rising". We could add another one for popular regions and cities, and from there you could subscribe or set them as a favorite from a user, either on the city/region feed or in the panel itself

**Comment by cubadomingo** [comment]
"in your state, trending, popular" etc.

I think that's a great idea bro.
