### ISSUE TITLE
Menu Bar Links

### ISSUE THREAD

**Issue by tmobaird** [cubadomingo/words_and_moves#43]
Couple problems with the Menu Bar as of right now, mainly because we haven't tackled much after a sign in yet. Currently when you're not signed in, the menu bar looks like this:

<img width="1252" alt="screen shot 2016-07-30 at 12 42 59 am" src="https://cloud.githubusercontent.com/assets/7366444/17268139/a5b22fd8-55ee-11e6-8efb-15032e1fb831.png">

and after a user signs in the menu looks exactly the same: 

<img width="1235" alt="screen shot 2016-07-30 at 12 43 18 am" src="https://cloud.githubusercontent.com/assets/7366444/17268143/bb00d880-55ee-11e6-8cc9-da571d1eb40d.png">

We should probably add some conditionals to the menu so that when a user is not signed in this menu appears, but when a user is signed in the "Sign in" and "Sign Up" links are not displayed, but a "Sign Out" button does

**Comment by cubadomingo** [comment]
So you know how the feed is going to be a black navbar? Well the side should have the username and dropdown for settings if the user is logged in, otherwise have a sign in and sign up button/link, and yeah we can just write an if else statement for that in the navbar view. Since we plan on only having that navbar for the landing page before redirecting to the region pages then we should probably get this navbar out of the application layout and place it direclty in the landing page/devise views. How does that sound?

**Comment by tmobaird** [comment]
Yeah that sounds good to me. We could create two separate partials for two different navbars then create something in the application erb that looks like this:

```ruby
<% if current_user.blank? %>
  <%= render "no_auth_navbar" %>
<% else %>
  <%= render "auth_navbar" %>
<% end %>
```

This would allow us to replace the "Feed" title in the navbar to be potentially anything

**Comment by cubadomingo** [comment]
Bro so I was thinking about not having the application layout render for the landing page controller and then place the navbar directly in the view such as I have it now, but your way of implementing is 1000 times better. Love the way you think man 💯

**Comment by tmobaird** [comment]
Thanks brotha ✊ 💯

**Comment by tmobaird** [comment]
Also another cool thing that I use to track what I'm working on is zenhub. It's a chrome extension that works with github so you can use taskboards to track your progress on the things you're working on. https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd?hl=en-US

**Comment by cubadomingo** [comment]
Created #45 for this
