### ISSUE TITLE
Unliking and Un-disliking

### ISSUE THREAD

**Issue by tmobaird** [cubadomingo/words_and_moves#47]
This functionality should probably be added. I think it's kinda sloppy when this functionality isn't implemented when liking/disliking is.

**Comment by tmobaird** [comment]
@cubadomingo I'm gonna open this up again. It's not done yet, but I plan on tackling this tomorrow

**Comment by cubadomingo** [comment]
no doubt bro, my bad 😀

**Comment by tmobaird** [comment]
all good home ✊

**Comment by cubadomingo** [comment]
Yo, so how would we display this? and update the score when a person clicks?

**Comment by tmobaird** [comment]
This shouldn't be too difficult. Basically if the user has liked or disliked a post/event simply change the button to be "Unlike" or "Undislike". Something similar to the way facebook does it. That will then go and destroy the like/dislike object for the user, which will update the count

**Comment by cubadomingo** [comment]
Cool got it!
