### ISSUE TITLE
NoMethodError when no events in region/post/:id

### ISSUE THREAD

**Issue by cubadomingo** [cubadomingo/words_and_moves#59]
So I get a NoMethodError when there is no event in the region. This could be fixes with a conditional I think,` if @events`

<img width="1009" alt="screen shot 2016-08-02 at 6 37 08 pm" src="https://cloud.githubusercontent.com/assets/15992549/17347849/68cdf5c6-58e0-11e6-8393-d6bb7597a051.png">

**Comment by tmobaird** [comment]
that shouldn't happen as long as `@events` is set to an array of events. Maybe something went wrong with the way events and or the loop through events is defined

**Comment by cubadomingo** [comment]
But what about new regions, where there are no events yet for example?

**Comment by tmobaird** [comment]
shouldn't be a problem. If there are not events then it should not even get into the loop.

For example:
```ruby
@events = []
for event in @events
  puts event.name
end
```
That won't print out anything because `@events` is an empty array so the loop won't have any iterations

**Comment by cubadomingo** [comment]
Okay so once again I effed up. I made a test post but never updated the event date, so it stayed at nil. So that's why it didn't work when strftime was called. I should have notice this too because with event.location it did get called succesfully. My bad bro. Gotta get my head out the gutter 😬
