### ISSUE TITLE
Add remaining Event and Post new views

### ISSUE THREAD

**Issue by cubadomingo** [cubadomingo/words_and_moves#66]
Let's be able to add events and posts, let's create the following views: new and edit. Along with adding the create & destroy links.

**Comment by cubadomingo** [comment]
Should I close this bro and include the specs for this in the other testing issue we have up?

**Comment by tmobaird** [comment]
Leave this open for a bit. I still have to do the events part

**Comment by cubadomingo** [comment]
I just did the events brother in the PR

**Comment by tmobaird** [comment]
Awesome! Nice work brotha!
