### ISSUE TITLE
Integrating React.

### ISSUE THREAD

**Issue by cubadomingo** [cubadomingo/words_and_moves#67]
I have a question bro. Should we create the controller actions and views for filtering, such as subregion and cities, or should we do the filtering in the same page through components in React. I know we're trying to get as much done with rails but I think it would be unnecessary work if we make the controller and action views, only to remove them once we start trying to integrate react.

**Comment by tmobaird** [comment]
I say right now we leave filtering out until we get the core functionalities working and tested. Then we can add the filtering. React would probably be a good way to go about this too.

**Comment by cubadomingo** [comment]
Okay cool, so just the showing the events and posts through regions for now, right?

**Comment by tmobaird** [comment]
Yep, once we get everything working solidly and cleanly we can start adding filters
