### ISSUE TITLE
Landing Page in Production.

### ISSUE THREAD

**Issue by cubadomingo** [cubadomingo/words_and_moves#8]
So I had an interaction yesterday that got me thinking on setting up the website in production. I was set to meet up with a friend at a mall yesterday after the meetup and had some down time so I decided to work on the site. As I was working on the template, a person sitting next to me was looking and struck up a conversation with me. I basically explained to him the idea and he though it was great. He loved the idea and was definitely interested in the site but I couldn't give him a proper date on when it would be ready to use. So I got to thinking, what if I set up the site in production and just have a landing page with the logo, a quick description of the app, along with the ability for a visitor to input his email and get notified when the site goes live. That way when the site goes live with all the features, we would already have a list of some potential users. What are your thoughts on this?

**Comment by tmobaird** [comment]
I actually think this is a great idea. Definitely be something good to have, a place that we can point people too for some info. A good idea on how to start with this might be to talk to Jay about it. He was talking to me a little bit yesterday about getting your CI server and everything else needed to deploy configured at the beginning of the dev cycle so you can put something out there. 

So, I'd slack Jay, or email him. He's pretty good about getting back to people.

**Comment by tmobaird** [comment]
This would still allow us to deploy everything we have to production very frequently, in an agile style. We would literally just have to set the root to our splash page, which would have no visible links to any of the actual applications actions.

**Comment by cubadomingo** [comment]
Alright, I have pretty good experience with creating a digital ocean VPS, installing and configuring the server with the OS, web and app server. I'll also install Capistrano so we could easily deploy the app with `cap production deploy`. Should have that done by today.

**Comment by tmobaird** [comment]
Awesome!! 👍 have you ever set that stuff up with a CI server like Travis? So it will run all of our tests and everything and deploy if they all pass.

**Comment by cubadomingo** [comment]
I actually went to a python meetup where they showed us how to set it up using flask. It wasn't too difficult and I don't think it should be much different for a Rails app. I'll try my hand at integrating Travis CI. Also I'm going to try to use Let's Encrypt so we can start using HTTPS, never used it before so I'll let you know how both go.

**Comment by tmobaird** [comment]
Nice! Sounds good! 👍 There should be plenty of docs on setting up a CI server w/ travis for a rails app.

**Comment by cubadomingo** [comment]
Just wanted to give a quick update. So TravisCI is up as you already know. I also just finished setting up the the whole server installation and added capistrano to the project. Cap Production Deploy is working smoothly. I'm now going to try to install Let's Encrypt for https and I'll be making a landing page that gets redirected to root.

My question to you is do yo know how we could implement the mailing list? I really have no experience when it comes to mailing and rails.

wordsandmoves.com is the domain name if you want to check it out. It's redirecting to the login page at the moment.

So I commented on the wrong issue haha. I posted them here again for better organization.

**Comment by tmobaird** [comment]
lol all good dude. And that's awesome brotha! Really great work 👏 👏. I checked out the domain and it's dope that it's already up and running.

Also I do know how to implement mailers in Rails, it's actually a lot easier than it appears. You can even format the email messages with html.erb files. If you checkout the Ruby on Rails homepage, the Rails 5 tutorial video should show you how to simply create them. But I can also help create them if you want help.

**Comment by cubadomingo** [comment]
Thanks bro, I'll take a look at the video!

**Comment by cubadomingo** [comment]
<img width="1232" alt="screen shot 2016-07-25 at 5 13 57 pm" src="https://cloud.githubusercontent.com/assets/15992549/17117687/4cff2f1e-528b-11e6-8943-e5a392b89cdc.png">

Hey bro, take a look at the landing page. We could change the color, I just want to know if the layout seems good. Any thoughts?

**Comment by tmobaird** [comment]
DUDE THAT LOOKS SO DOPE! I love it! Not sure if you're gonna open up the scope, but a good category to add might be 'Sports'

**Comment by cubadomingo** [comment]
Good idea bro, I'll make a vector for sports and add another column.

**Comment by cubadomingo** [comment]
<img width="1801" alt="screen shot 2016-07-25 at 5 46 11 pm" src="https://cloud.githubusercontent.com/assets/15992549/17118748/149080c4-5290-11e6-9e84-c62a4a0797c6.png">
Alright Here's the updated version, and here's the mobile version.
<img width="401" alt="screen shot 2016-07-25 at 5 46 30 pm" src="https://cloud.githubusercontent.com/assets/15992549/17118782/47c388b0-5290-11e6-9c61-22ae64c26a8b.png">

**Comment by tmobaird** [comment]
:+1: :+1: :+1:

**Comment by cubadomingo** [comment]
Quick update: so I managed to deploy the most recent merge to master and it looks pretty nice, other than the fact that 3 img links are broken right now which I will get to tomorrow. You can also check out /users/sign_in and it also looks pretty fucking nice. I'm juiced. 

In terms of the active mailer and mailgun question you asked earlier, I was planning on using MailGun to be able to send the email through an @updates.wordsandmoves.com address. I still planned on using active mailer for the erb styling. I'm following this [guide](https://launchschool.com/blog/handling-emails-in-rails).

**Comment by tmobaird** [comment]
Hell yeah dude! That's awesome! I'm gonna work on the sign up and forgot password pages tomorrow to make those look similar to the sign in page. It's looking pretty dope so far! Let's keep it rollin'.

And that sounds good! I'll take a look at that guide. Thanks brotha 👍

**Comment by cubadomingo** [comment]
👐👐
